### ISSUE TITLE
How can Inject Google font in Nuxt3?

### ISSUE THREAD

**Issue by saeedata** [stafyniaksacha/vite-plugin-fonts#28]
Hi, is there any way to inject fonts in Nuxt3?
I was wondering bout this sentence in the doc:
⚠️ This will not inject Google/Typekit fonts, only custom fonts will be loaded.

**Comment by stafyniaksacha** [comment]
There are some tips here: https://github.com/stafyniaksacha/vite-plugin-fonts/issues/9
