### ISSUE TITLE
Nuxt3 Support

### ISSUE THREAD

**Issue by pisandelli** [stafyniaksacha/vite-plugin-fonts#9]
Hello guys! I tried to add the plugin into a NUXT3 app using vite, but it seems not to be working.  Am I doing something wrong? I'm using the latest version (RC4) from Nuxt3. 
My `nuxt.config.ts` is like this:

```javascript
import { defineNuxtConfig } from 'nuxt'
import { VitePluginFonts } from 'vite-plugin-fonts'

export default defineNuxtConfig({

  vite: {
    plugins: [
      VitePluginFonts({
        google: {
          families: [{name:'Barlow', styles:'wght@100;300;400'}]
        },
      })
    ]
  }

})

```

**Comment by pisandelli** [comment]
Hello! Any help?
Thanks in advance.

**Comment by rwwagner90** [comment]
@pisandelli Did you ever figure this out? What is not working exactly? For me, I get a 404. `GET http://localhost:3000/_nuxt/@vite-plugin-fonts/fonts.css net::ERR_ABORTED 404 (Not Found)`

**Comment by stafyniaksacha** [comment]
This plugin can not work with nuxt3 since it uses [`transformIndexHtml`](https://github.com/stafyniaksacha/vite-plugin-fonts/blob/main/src/index.ts#L28) vite function which is not used by nuxt

We have to create a nuxt3 module which injects tags inside the nuxt `app.head` config

**Comment by pisandelli** [comment]
> @pisandelli Did you ever figure this out? What is not working exactly? For me, I get a 404. `GET http://localhost:3000/_nuxt/@vite-plugin-fonts/fonts.css net::ERR_ABORTED 404 (Not Found)`

Hey @rwwagner90 for me the fonts are not being added.
But with this answer from @stafyniaksacha everything make sense now.
I'm using [useHead](https://github.com/vueuse/head#api) from VueUse as a solution.

Thanks for @stafyniaksacha for clarifying this issue.

**Comment by rwwagner90** [comment]
I just manually added my fonts to the `app.head` config for now. @pisandelli do you have an example to share of how to make this work?

**Comment by stafyniaksacha** [comment]
For nuxt and google font you can use this:

```ts
import { defineNuxtConfig } from 'nuxt'

export default defineNuxtConfig({
  app: {
    head: {
      link: [
        { rel: 'preconnect', href: 'https://fonts.googleapis.com' },
        {
          rel: 'preconnect',
          href: 'https://fonts.gstatic.com',
          crossorigin: true,
        },
        {
          rel: 'stylesheet',
          href: 'https://fonts.googleapis.com/css2?family=Roboto+Flex:wght@200..800&display=swap',
        },
      ],
    },
  },
})
```

**Comment by pisandelli** [comment]
I'm using a composable

```
//composabels/useGoogleFonts.ts

import { useHead } from '@vueuse/head'

export function useGoogleFonts() {
  useHead({
    link: [
      {
        rel: 'preconnect',
        href: 'https://fonts.googleapis.com'
      },
      {
        rel: 'preconnect',
        href: 'https://fonts.gstatic.com',
        crossorigin: 'crossorigin'
      },
      {
        rel: 'stylesheet',
        href: 'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&display=swap'
      }
    ],
  })
}
```

And call it in my app.vue

```
<script lang="ts" setup>
 import { useGoogleFonts } from './composables/useGoogleFonts'
 useGoogleFonts()
</script>
```
